### ISSUE TITLE
No results displayed

### ISSUE THREAD

**Issue by gdnathan** [luc-tielen/telescope_hoogle#3]
Opening a new issue to centralize people from issue #2 who had no result on search

I still have no result as of today. (Manjaro WSL, nvim 0.6)

**Comment by luc-tielen** [comment]
@gdnathan Right now I have very little free time to maintain this plugin. But I would welcome a PR that fixes it!

**Comment by gdnathan** [comment]
Okay, ill look into it. 

where can i ask you question about the code?

**Comment by luc-tielen** [comment]
Via this github issue, or on Twitter via private message (@luctielen). Or my email, if you know where to look. ;)
